'use client'
import { useResource } from '../core/session'
import type { Metrics as MetricsType } from '../core/types'
import { Card, Empty } from '../shared/ui'
import { Heading, Resource, Stats, duration } from './common'
import styles from './workspace.module.scss'
export function Metrics() {
  const metrics = useResource<MetricsType>('/metrics')
  return <><Heading title="Menos repetición. Resultados visibles." description="Números calculados a partir del historial de este workspace." /><Resource resource={metrics}>{data => <><Stats metrics={data} />{data.manualCompleted + data.assistedCompleted === 0 && <Card><Empty title="Sin traspasos verificados todavía">Los indicadores se completarán cuando haya resultados. No necesitás cargar datos de ejemplo.</Empty></Card>}<div className={styles.columns} style={{ marginTop: 24 }}><Card><h2>De la oferta al documento</h2>{[['Ofertas realizadas', data.offered], ['Guardados aprobados', data.approved], ['Traspasos rechazados', data.rejected], ['Ofertas silenciadas', data.dismissed]].map(([label, value]) => <div className={styles.row} key={label}><span>{label}</span><strong>{value}</strong></div>)}<p className={styles.note}>Un guardado aprobado cuenta como resultado solo cuando el documento se lee de vuelta desde Ambiguous.</p></Card><Card><h2>Cómo se hicieron los traspasos</h2><div className={styles.comparison}><span>Manuales</span><strong>{data.manualCompleted}</strong></div><div className={styles.meter}><span style={{ width: `${data.manualCompleted / Math.max(1, data.manualCompleted + data.assistedCompleted) * 100}%` }} /></div><div className={styles.comparison}><span>Asistidos</span><strong>{data.assistedCompleted}</strong></div><div className={styles.meter}><span style={{ width: `${data.assistedCompleted / Math.max(1, data.manualCompleted + data.assistedCompleted) * 100}%` }} /></div><p className={styles.note}>Mediana manual: {duration(data.medianManualDurationMs)}<br />Eventos de observación conservados: {data.observedEvents}</p></Card></div><p className={styles.metricNote}>El ahorro es una estimación: compara la duración de cada traspaso asistido verificado con la mediana manual de su oferta. Incluye el tiempo de revisión y espera. Un guion (—) indica que todavía no hay evidencia suficiente. El historial puede contener ensayos anteriores.</p></>}</Resource></>
}
